### Querying Data: American Community Survey, 5-Year Estimate Detailed Tables

The entry-point for the `acspsuedo` package is the `query` module, particularly the `download()` and `async_download()` functions.

In [2]:
import acspsuedo.query as apq

`acspsuedo` makes use of two models to run queries to the Census Bureau: a standard/synchronous model and an asynchronous concurrent model (built around the built-in `async` library with the `aiohttp.ClientSession` context manager).

URL queries are naturally I/O bound processes, which is why this particular choice of a coroutine execution unit is very much suitable.

A standard query might look something like this.

In [4]:
from acspsuedo.datasets import ACS5
from acspsuedo.fips.states import CA

df = apq.download(
    dataset = ACS5,
    year = 2023,
    tables = 'B25058',
    state = CA,
    tract = '*'
)

df

,NAME,STATE,COUNTY,TRACT,YEAR,B25058_001E,B25058_001M
0,Census Tract 4001; Alameda County; California,06,001,400100,2023,3501.0,NaN
1,Census Tract 4002; Alameda County; California,06,001,400200,2023,2795.0,640.0
2,Census Tract 4003; Alameda County; California,06,001,400300,2023,2051.0,370.0
3,Census Tract 4004; Alameda County; California,06,001,400400,2023,2431.0,245.0
4,Census Tract 4005; Alameda County; California,06,001,400500,2023,2042.0,222.0
...,...,...,...,...,...,...,...
9124,Census Tract 409.02; Yuba County; California,06,115,040902,2023,2410.0,134.0
9125,Census Tract 410.01; Yuba County; California,06,115,041001,2023,905.0,413.0
9126,Census Tract 410.02; Yuba County; California,06,115,041002,2023,NaN,NaN
9127,Census Tract 411.01; Yuba County; California,06,115,041101,2023,638.0,70.0
9128,Census Tract 411.02; Yuba County; California,06,115,041102,2023,NaN,NaN

With the asynchronous approach:

In [5]:
df = await apq.async_download(
    dataset = ACS5,
    year = 2023,
    tables = 'B25058',
    state = CA,
    tract = '*'
)

df

,NAME,STATE,COUNTY,TRACT,YEAR,B25058_001E,B25058_001M
0,Census Tract 4001; Alameda County; California,06,001,400100,2023,3501.0,NaN
1,Census Tract 4002; Alameda County; California,06,001,400200,2023,2795.0,640.0
2,Census Tract 4003; Alameda County; California,06,001,400300,2023,2051.0,370.0
3,Census Tract 4004; Alameda County; California,06,001,400400,2023,2431.0,245.0
4,Census Tract 4005; Alameda County; California,06,001,400500,2023,2042.0,222.0
...,...,...,...,...,...,...,...
9124,Census Tract 409.02; Yuba County; California,06,115,040902,2023,2410.0,134.0
9125,Census Tract 410.01; Yuba County; California,06,115,041001,2023,905.0,413.0
9126,Census Tract 410.02; Yuba County; California,06,115,041002,2023,NaN,NaN
9127,Census Tract 411.01; Yuba County; California,06,115,041101,2023,638.0,70.0
9128,Census Tract 411.02; Yuba County; California,06,115,041102,2023,NaN,NaN

The asynchronous approach may be favorable under the circumstances of:

1. **Querying large amounts of data**, such as an ETL/ELT process or data pipeline


2. **A user-defined API key**, since API key allows for 500+ queries in a single session
    - To learn more about setting up your API key, check out the `API_Key.ipynb` notebook