## United States-Scope Data

Additional FIPS specifiers are not required if a user wishes to view data for collections of geographies from the `us` upper-level/parent scope.

This default behavior for querying such data raises a `UserWarning`.

In [2]:
import acspsuedo.data as apd
from acspsuedo.api import ACS1

In [3]:
df = await apd.download_by_geo_collection(
    api  = ACS1,
    year = 2023,
    dataset = 'B25058',
    geography = 'state',
)

df.head(5)

/Users/raminderdubb/PyScripts/acspsuedo/acspsuedo/data.py:336: UserWarning: Could not find any fully-specificied paths. Defaulting to a partially specificied path with upper-level/parent scope of 'us'
  pathspec = FipsFMT.infer_path(api, year, geography, **kwargs)

         NAME        ucgid GEOID B25058_001E B25058_001M
0     Alabama  0400000US01    01         757          15
1      Alaska  0400000US02    02        1242          33
2     Arizona  0400000US04    04        1438          18
3    Arkansas  0400000US05    05         721          10
4  California  0400000US06    06        1820           7

Warnings can be toggled off with `ignore_warning`.

In [5]:
df = await apd.download_by_geo_collection(
    api  = ACS1,
    year = 2023,
    dataset = 'B25058',
    geography = 'state',
    ignore_warning = True
)

df.head(5)

         NAME        ucgid GEOID B25058_001E B25058_001M
0     Alabama  0400000US01    01         757          15
1      Alaska  0400000US02    02        1242          33
2     Arizona  0400000US04    04        1438          18
3    Arkansas  0400000US05    05         721          10
4  California  0400000US06    06        1820           7