### Viewing Dataset/Variable Metadata: American Community Survey 1-Year Public Use Microdata Sample

For end-users, you may be unsure as to what type of data you might be looking for.

<br>

To that end, `'acspsuedo.query'` provides a friendly `variable_cache` interface to view metadata on all available variables and tables for a dataset.

*Note: Navigating dataset metadata is purposefully conducted via this interface since this interface is employed as part of making queries to the Census Bureau. By pre-exploring the data, users can more quickly and correctly send queries to the Census Bureau.*

In [4]:
import acspsuedo.query as apq

variable_cache = apq.variable_cache

from acspsuedo.datasets import ACS1_PUMS

DATASET = ACS1_PUMS
YEAR = 2014

#### Fetching metadata on all variables

The `var_metadata_df()` method of the interface provides holistic information on all variables supported by the dataset in question, with such information covering:

- The name of the variable

- The variable's corresponding label

- The data type of the variable, and

- What tables contain that variable

In [5]:
VARIABLE_METADATA_DF = variable_cache.var_metadata_df(DATASET, YEAR)

VARIABLE_METADATA_DF

,DATASET,YEAR,VARIABLE,LABEL,VARIABLE_TYPE,TABLE,TOPIC
0,acs/acs1/pums,2014,ACCESS,Access to the Internet,int,N/A,
1,acs/acs1/pums,2014,ACR,Lot size,int,N/A,
2,acs/acs1/pums,2014,ADJHSG,Adjustment factor for housing dollar amounts (...,int,N/A,
3,acs/acs1/pums,2014,ADJINC,Adjustment factor for income and earnings doll...,int,N/A,
4,acs/acs1/pums,2014,AGEP,Age,int,N/A,
...,...,...,...,...,...,...,...
508,acs/acs1/pums,2014,WKW,Weeks worked during past 12 months,int,N/A,
509,acs/acs1/pums,2014,WORKSTAT,Work status of householder or spouse in family...,int,N/A,
510,acs/acs1/pums,2014,WRK,Worked last week,int,N/A,
511,acs/acs1/pums,2014,YBL,When structure first built,int,N/A,
512,acs/acs1/pums,2014,YOEP,Year of entry,int,N/A,

*Note: Public use microdata samples do not have topics or tables. However, for other datasets, such as the American Community Survey 1-Year or 5-Year Detailed Tables, this is the case.*

Suppose you might be interested in variables covering earnings or income. You can find variables pertaining to those topics as so.

In [6]:
TOPICS = ['income', 'earnings']

VARIABLE_METADATA_DF[
    VARIABLE_METADATA_DF['LABEL'].str.contains('|'.join(TOPICS))
]

,DATASET,YEAR,VARIABLE,LABEL,VARIABLE_TYPE,TABLE,TOPIC
3,acs/acs1/pums,2014,ADJINC,Adjustment factor for income and earnings doll...,int,N/A,
70,acs/acs1/pums,2014,FFINCP,Family income (past 12 months) allocation flag,int,N/A,
82,acs/acs1/pums,2014,FHINCP,Household income (past 12 months) allocation flag,int,N/A,
88,acs/acs1/pums,2014,FHINS4P,"Medicaid, medical assistance, or any kind of g...",int,N/A,
96,acs/acs1/pums,2014,FINCP,"Family income (past 12 months, use ADJINC to a...",int,N/A,
99,acs/acs1/pums,2014,FINTP,"Interest, dividend, and net rental income allo...",int,N/A,
128,acs/acs1/pums,2014,FOIP,All other income allocation flag,int,N/A,
130,acs/acs1/pums,2014,FPAP,Public assistance income allocation flag,int,N/A,
132,acs/acs1/pums,2014,FPERNP,Total person's earnings allocation flag,int,N/A,
133,acs/acs1/pums,2014,FPINCP,Total person's income (signed) allocation flag,int,N/A,
143,acs/acs1/pums,2014,FRETP,Retirement income allocation flag,int,N/A,
154,acs/acs1/pums,2014,FSEMP,Self-employment income allocation flag,int,N/A,
162,acs/acs1/pums,2014,FSSP,Social Security income allocation flag,int,N/A,
172,acs/acs1/pums,2014,FWAGP,Wages and salary income allocation flag,int,N/A,
185,acs/acs1/pums,2014,GRPIP,Gross rent as a percentage of household income...,int,N/A,
191,acs/acs1/pums,2014,HINCP,"Household income (past 12 months, use ADJINC t...",int,N/A,
195,acs/acs1/pums,2014,HINS4,"Medicaid, Medical Assistance, or any kind of g...",int,N/A,
207,acs/acs1/pums,2014,INTP,"Interest, dividends, and net rental income pas...",int,N/A,
262,acs/acs1/pums,2014,OCPIP,Selected monthly owner costs as a percentage o...,int,N/A,
263,acs/acs1/pums,2014,OIP,All other income past 12 months (use ADJINC to...,int,N/A,
266,acs/acs1/pums,2014,PAP,PUMS SSI/AFDC/other welfare income,int,N/A,
268,acs/acs1/pums,2014,PERNP,Total person's earnings,int,N/A,
269,acs/acs1/pums,2014,PINCP,Total person's income (signed),int,N/A,
381,acs/acs1/pums,2014,RETP,Retirement income past 12 months (use ADJINC t...,int,N/A,
393,acs/acs1/pums,2014,SEMP,"Self-employment income past 12 months (signed,...",int,N/A,
420,acs/acs1/pums,2014,WAGP,Wages or salary income past 12 months (use ADJ...,int,N/A,

From there, you can run queries for data or continue to explore the metadata further.

In our case, we will choose the `WAGP` (use ADJINC to adjust WAGP to constant dollars) and the `PAP` (PUMS SSI/AFDC/other welfare income) variables to run a mock query.

Also, since the PUMS data covers record-like information on individual persons and housing units, it is recommended to add two identification variables:
- `SERIALNO` (Housing unit/GQ person serial number)
- `SPORDER` (Person number)

*For further reference on PUMS guidelines, see [https://www.census.gov/programs-surveys/acs/microdata/access.html](https://www.census.gov/programs-surveys/acs/microdata/access.html)*

In [7]:
SELECTED_VARIABLES = [
    'SERIALNO',
    'SPORDER',
    'WAGP',
    'PAP'
]

In [8]:
# First, view supported geographic specifiers for our dataset

apq.view_geographic_paths(DATASET, YEAR)

[['region'], ['division'], ['state'], ['state', 'public_use_microdata_area']]

In [ ]:
# We select ['state', 'public_use_microdata_area'] and run our query

from acspsuedo.fips.states import CA # <- Abbreviation for California

df = apq.download(
    dataset = DATASET,
    year = YEAR,
    variables = SELECTED_VARIABLES,
    state = CA,
    public_use_microdata_area = '*'
)

df

       STATE PUBLIC_USE_MICRODATA_AREA SERIALNO SPORDER  YEAR PAP   WAGP
0          6                       101  1000158       1  2014   0      0
1          6                       101   100030       1  2014   0   9800
2          6                       101   100030       2  2014   0  59000
3          6                       101   100030       3  2014   0      0
4          6                       101   100030       4  2014  -1     -1
...      ...                       ...      ...     ...   ...  ..    ...
372548     6                      9904   984444       1  2014   0  75000
372549     6                      9904   985466       1  2014   0  18000
372550     6                      9904   991672       1  2014   0      0
372551     6                      9904   991981       1  2014   0      0
372552     6                      9904   995683       1  2014   0  18000

[372553 rows x 7 columns]